title: My awesome title
author: GitHub User Patrick Cusick
email: patricktcusick@gmail.com
description: I like everything Bagels
    Clownboy says yeehonk
theme: minima
# social links
twitter_username: @theavgswimmer
github_username:  @ptcusick

show_excerpts: true # set to false to remove excerpts on the homepage

